### ISSUE TITLE
Replace Bootstrap blue with Plone blue

### ISSUE THREAD

**Issue by Netroxen** [collective/plonetheme.tokyo#14]
As a user,
I want to see the familiar Plone blue on core elements,
so I can distinguish the platform.

# Acceptance Criteria

Plone blue: #007BB1

* It's done when the site links use the Plone blue
* It's done when the site header uses Plone blue
* It's done when the info portal message uses Plone blue
* It's done when the primary buttons / inputs use Plone blue

**Comment by sarn0ld** [comment]
Caution: As we are not adding Bootstrap4 as a Resource Bundle we can not just override the color by importing bootstrap in the tokyo less... That means this can not be done as a one-liner...
Either we add a bootstrap bundle or we do a lot of css overrides manually...
