### ISSUE TITLE
Is that possible to modify the CSS TTW?

### ISSUE THREAD

**Issue by mactrash** [collective/plonetheme.tokyo#51]
I am need to this, can you point me to the doc about how to do that?

**Comment by santonelli** [comment]
Unfortunately there is no option to edit CSS TTW. Plone 6 will have an [option](https://training.plone.org/5/theming/ttw_customizations.html#customize-css-variables) where you can edit CSS in the site setup. plonetheme.tokyo will be available for Plone 6 as well.
